python ./quadJSONsmall.py ./uploads/aripa/img/resourcesDynamic/images/layer 90   961 768 > ./uploads/aripa/img/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/moneal/Human_Excretory_System/resourcesDynamic/images/layer 90   990 768 > ./uploads/moneal/Human_Excretory_System/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/moneal/Eudicot_Stem/resourcesDynamic/images/layer 90   1024 507 > ./uploads/moneal/Eudicot_Stem/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/moneal/DNA_Structure/resourcesDynamic/images/layer 90   600 641 > ./uploads/moneal/DNA_Structure/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/moneal/Monocot_Stem/resourcesDynamic/images/layer 90   740 800 > ./uploads/moneal/Monocot_Stem/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/moneal/Eudicot_Root/resourcesDynamic/images/layer 90   827 768 > ./uploads/moneal/Eudicot_Root/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/moneal/Amino_Acid/resourcesDynamic/images/layer 90   455 556 > ./uploads/moneal/Amino_Acid/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/moneal/Free_Energy_Diagram/resourcesDynamic/images/layer 90   1689 1300 > ./uploads/moneal/Free_Energy_Diagram/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/moneal/Human_Respiratory_System/resourcesDynamic/images/layer 90   962 768 > ./uploads/moneal/Human_Respiratory_System/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/moneal/Phylogenetic_Tree/resourcesDynamic/images/layer 90   621 272 > ./uploads/moneal/Phylogenetic_Tree/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/moneal/Flower/resourcesDynamic/images/layer 90   787 768 > ./uploads/moneal/Flower/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/moneal/Monocot_Root/resourcesDynamic/images/layer 90   961 768 > ./uploads/moneal/Monocot_Root/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/moneal/Bird_or_Mammal_Heart/resourcesDynamic/images/layer 90   705 768 > ./uploads/moneal/Bird_or_Mammal_Heart/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/moneal/Fish_Heart/resourcesDynamic/images/layer 90   800 890 > ./uploads/moneal/Fish_Heart/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/moneal/Amphibian_Heart/resourcesDynamic/images/layer 90   1024 738 > ./uploads/moneal/Amphibian_Heart/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/avdao/bacteriophage/resourcesDynamic/images/layer 90   2789 2176 > ./uploads/avdao/bacteriophage/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/avdao/PackagingBacteriophageDNA/resourcesDynamic/images/layer 90   2699 1726 > ./uploads/avdao/PackagingBacteriophageDNA/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/avdao/GelElectrophoresis/resourcesDynamic/images/layer 90   2799 2114 > ./uploads/avdao/GelElectrophoresis/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/Human_Excretory_System/resourcesDynamic/images/layer 90   990 768 > ./uploads/gazheng/Human_Excretory_System/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/Eudicot_Stem/resourcesDynamic/images/layer 90   1024 507 > ./uploads/gazheng/Eudicot_Stem/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/DNA_Structure/resourcesDynamic/images/layer 90   600 641 > ./uploads/gazheng/DNA_Structure/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/Snow_white/resourcesDynamic/images/layer 90   400 240 > ./uploads/gazheng/Snow_white/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/Monocot_Stem/resourcesDynamic/images/layer 90   740 800 > ./uploads/gazheng/Monocot_Stem/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/Eudicot_Root/resourcesDynamic/images/layer 90   827 768 > ./uploads/gazheng/Eudicot_Root/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/Cardiology/resourcesDynamic/images/layer 90   1795 1650 > ./uploads/gazheng/Cardiology/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/Amino_Acid/resourcesDynamic/images/layer 90   455 556 > ./uploads/gazheng/Amino_Acid/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/Free_Energy_Diagram/resourcesDynamic/images/layer 90   1689 1300 > ./uploads/gazheng/Free_Energy_Diagram/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/Human_Respiratory_System/resourcesDynamic/images/layer 90   962 768 > ./uploads/gazheng/Human_Respiratory_System/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/Phylogenetic_Tree/resourcesDynamic/images/layer 90   621 272 > ./uploads/gazheng/Phylogenetic_Tree/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/Flower/resourcesDynamic/images/layer 90   787 768 > ./uploads/gazheng/Flower/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/Monocot_Root/resourcesDynamic/images/layer 90   961 768 > ./uploads/gazheng/Monocot_Root/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/Bird_or_Mammal_Heart/resourcesDynamic/images/layer 90   705 768 > ./uploads/gazheng/Bird_or_Mammal_Heart/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/Fish_Heart/resourcesDynamic/images/layer 90   800 890 > ./uploads/gazheng/Fish_Heart/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/gazheng/Amphibian_Heart/resourcesDynamic/images/layer 90   1024 738 > ./uploads/gazheng/Amphibian_Heart/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/jmeurlin/diagram_virus/resourcesDynamic/images/layer 90   600 565 > ./uploads/jmeurlin/diagram_virus/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/pstdenis/img/resourcesDynamic/images/layer 90   961 768 > ./uploads/pstdenis/img/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/pstdenis/GelElectrophoresis/resourcesDynamic/images/layer 90   2799 2114 > ./uploads/pstdenis/GelElectrophoresis/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/pstdenis/Dr_B_Test_Amandas_edit/resourcesDynamic/images/layer 90   1000 1050 > ./uploads/pstdenis/Dr_B_Test_Amandas_edit/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/mwitherspoon/GelElectrophoresis/resourcesDynamic/images/layer 90   2799 2114 > ./uploads/mwitherspoon/GelElectrophoresis/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/rasondhi/img/resourcesDynamic/images/layer 90   961 768 > ./uploads/rasondhi/img/resourcesDynamic/imageMap.json
python ./quadJSONsmall.py ./uploads/rasondhi/img2/resourcesDynamic/images/layer 90   961 360 > ./uploads/rasondhi/img2/resourcesDynamic/imageMap.json
